# Generated by Django 2.1.1 on 2018-09-15 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='created_at',
        ),
    ]
