# Generated by Django 2.1.1 on 2018-09-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20180915_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/projectimg'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='media/projectimg'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='media/projectimg'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='media/projectimg'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='media/projectimg'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_main',
            field=models.ImageField(blank=True, null=True, upload_to='media/projectimg'),
        ),
        migrations.AlterField(
            model_name='project',
            name='intext_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/projectthumb'),
        ),
    ]
