# Generated by Django 2.1.1 on 2018-09-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20180917_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('resume_text', models.TextField()),
                ('featured_projects', models.ManyToManyField(blank=True, to='projects.Project')),
            ],
        ),
    ]
